/* Each new term in the Fibonacci sequence is generated by adding the previous two term. By starting with 1 and 2, the
first 10 terms will be :

 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
 even-valued terms. */

public class EvenFibonacciNumbers extends BaseProblem implements BaseProblemIfc {
    EvenFibonacciNumbers() {
        super(2);
    }

    @Override
    public String solve() {
        int number1 = 1;
        int number2 = 2;
        int sum;
        int total = 2;

        while (number2 < 4000000) {
            sum = number1 + number2;
            number1 = number2;
            number2 = sum;

            if (sum % 2 == 0) {
                total += sum;
            }
        }

        return String.valueOf(total);
    }
}